const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost/finalProjectDB', {
  useNewUrlParser: true,
});

const Meal = require('./meal');
const Restaurant = require('./Restaurant');
const User = require('./User');

const u1 = new User({
  username: 'bashar',
  password: 'bashar',
  phone: '0599123123',
  email: 'bas@gmail.com',
});

const u2 = new User({
  username: 'anwar',
  password: 'anwar',
  phone: '0599123123',
  email: 'anwar@gmail.com',
});

const u3 = new User({
  username: 'luai',
  password: 'luai',
  phone: '0599123123',
  email: 'luai@gmail.com',
});

const u4 = new User({
  username: 'roaa',
  password: 'roaa',
  phone: '0599123123',
  email: 'roaa@gmail.com',
});

u1.save();
u2.save();
u3.save();
u4.save();

const res = [
  {
    name: 'SHRAK DINNING',
    meals: [],
    img: 'shrak.png',
    description:
      'Located in the heart of Q-Center, the savory smell of freshly grilled shawarma will tinkle your taste buds, and you won’t stop at just one.',
    workHours: '10am - 5pm',
  },
  {
    name: 'LILAC DINNING',
    meals: [],
    img: 'lilac.png',
    description:
      'The Italian corner at the heart of Q-Center, Lailac offers pastries on a whole new level, it offers variety of fresh baked goodies that will satisfy all taste buds, in addition to different types of pasta, at convenient prices.',
    workHours: '10am - 8pm',
  },
  {
    name: 'SIROTER DINNING',
    meals: [],
    img: 'SIROTER.png',
    description:
      "Siroter is Rawabi's special café/restaurant for those of sophisticated taste and have special liking of French and Italian cuisines, it’s French themed where you can enjoy a cup of coffee, a meal or French baked goodies.",
    workHours: '10am - 8pm',
  },
  {
    name: 'JUICE BANG BANG DINNING',
    meals: [],
    img: 'JUICE BANG BANG.png',
    description:
      "Juicebangbang offers quality fresh juices and bubble smoothies. Bubble smoothies are fun beverages, characterized by the addition of tapioca balls to fresh brewed iced tea, iced coffee or smoothies. You simply sip your drink while you chew the balls sitting at the bottom of the cup - at the same time, it's a delightfully refreshing adventure! Visit the first Palestinian Branch for the brand that is located at the QCenter",
    workHours: '10am - 11pm',
  },
  {
    name: 'CHOCOLATE SHOP DINNING',
    meals: [],
    img: 'CHOCOLATE SHOP.png',
    description:
      'A haven for all the chocolate addicts out there! If you love Nutella this is the place for you offering crepes, waffles, churros, and even Lokomma covered with Nutella, Lotus Biscof, white chocolate and many other toppings you can dream of. All you can feel after a visit to our second branch at the QCenter is a sugar rush and an overdose of happiness.',
    workHours: '10am - 11pm',
  },
  {
    name: 'SHISHAPRESSO DINNING',
    meals: [],
    img: 'SHISHAPRESSO.png',
    description:
      'A local popular restau-café with their second branch located at QCenter, Shishapresso combines East and West. From main courses, light deserts, to fresh beverages and, most importantly, coffee, as well they are well known for their diverse variety of premium shishas (Hookah), a place for every taste you will for sure leave with a full belly and a smile on your face.',
    workHours: '10am - 12pm',
  },
];

const SHRAK = [
  {
    name: 'Chicken Shawarma Plate',
    price: 18,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 175,
    img: '1.jpg',
    cookingTime: 10,
    orderCounter: 43,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 23,
  },
  {
    name: 'Meat or Mix Shawarma Plate',
    price: 22,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 178,
    img: '2.jpg',
    cookingTime: 10,
    orderCounter: 64,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 33,
  },
  {
    name: 'Hummus plate with chicken shawarma',
    price: 22,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 505,
    img: '3.jpg',
    cookingTime: 10,
    orderCounter: 51,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 27,
  },
  {
    name: 'Hummus plate with meat or mix shawarma',
    price: 25,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 513,
    img: '4.jpg',
    cookingTime: 10,
    orderCounter: 32,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 19,
  },
  {
    name: 'hummus plate',
    price: 7,
    description: ' ',
    category: ['break fast'],
    type: 'food',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 310,
    img: '5.jpg',
    cookingTime: 6,
    orderCounter: 462,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 169,
  },
  {
    name: 'bean plate',
    price: 7,
    description: ' ',
    category: ['break fast'],
    type: 'food',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 310,
    img: '26.jpg',
    cookingTime: 6,
    orderCounter: 78,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 56,
  },
  {
    name: 'rosary bowl',
    price: 12,
    description: ' ',
    category: ['break fast'],
    type: 'food',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 280,
    img: '6.jpg',
    cookingTime: 6,
    orderCounter: 51,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 13,
  },
  {
    name: 'Cappy',
    price: 3,
    description: ' ',
    category: ['break fast'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 80,
    img: 'juice.jpg',
    cookingTime: 1,
    orderCounter: 1063,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 758,
  },
  {
    name: 'Soft drinks',
    price: 3,
    description: ' ',
    category: ['lunch'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 130,
    img: 'drinks.jpg',
    cookingTime: 1,
    orderCounter: 1203,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 931,
  },
  {
    name: 'Shawarma Beef Shrak Sandwich',
    price: 15,
    description: ' ',
    category: ['break fast'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 540,
    img: '7.jpg',
    cookingTime: 8,
    orderCounter: 177,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 89,
  },
  {
    name: 'Chicken Shawarma Shrak Sandwich',
    price: 13,
    description: ' ',
    category: ['break fast'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 540,
    img: '8.jpg',
    cookingTime: 8,
    orderCounter: 145,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 96,
  },
  {
    name: 'Meat Shawarma Sandwich',
    price: 12,
    description: ' ',
    category: ['break fast'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 500,
    img: '9.jpg',
    cookingTime: 7,
    orderCounter: 79,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 20,
  },
  {
    name: 'Kmaj Chicken Shawarma Sandwich',
    price: 11,
    description: ' ',
    category: ['break fast'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 500,
    img: '10.jpg',
    cookingTime: 7,
    orderCounter: 46,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 12,
  },
  {
    name: 'Falafel sandwich',
    price: 5,
    description: ' ',
    category: ['break fast'],
    type: 'food',
    sensitivity: [
      { vegan: true },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 380,
    img: '11.jpg',
    cookingTime: 6,
    orderCounter: 1835,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 867,
  },
  {
    name: 'Falafel',
    price: 1,
    description: ' ',
    category: ['break fast'],
    type: 'food',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 50,
    img: '12.jpg',
    cookingTime: 10,
    orderCounter: 511,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 207,
  },
];

const LILAC = [
  {
    name: 'vegetable pizza',
    price: 10,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: true },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 620,
    img: '13.jpg',
    cookingTime: 12,
    orderCounter: 23,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 7,
  },
  {
    name: 'Chicken BBQ Pizza',
    price: 15,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 700,
    img: '14.jpg',
    cookingTime: 12,
    orderCounter: 51,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 25,
  },
  {
    name: 'Alfredo pizza with chicken',
    price: 15,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 610,
    img: '15.jpg',
    cookingTime: 13,
    orderCounter: 18,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 5,
  },
  {
    name: 'Jalapeno pizza with chicken',
    price: 10,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 700,
    img: '16.jpg',
    cookingTime: 15,
    orderCounter: 41,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 35,
  },
  {
    name: 'Supreme Pizza',
    price: 10,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: true },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 500,
    img: '17.jpg',
    cookingTime: 11,
    orderCounter: 11,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 7,
  },
  {
    name: 'pepperoni pizza',
    price: 15,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 740,
    img: '18.jpg',
    cookingTime: 14,
    orderCounter: 82,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 49,
  },
  {
    name: 'Margherita pizza',
    price: 10,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: true },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 500,
    img: '19.jpg',
    cookingTime: 13,
    orderCounter: 31,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 15,
  },
  {
    name: 'Fettuccine',
    price: 17,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 860,
    img: '20.jpg',
    cookingTime: 20,
    orderCounter: 12,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 4,
  },
  {
    name: 'Fettuccine with chicken',
    price: 25,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 900,
    img: '21.jpg',
    cookingTime: 22,
    orderCounter: 7,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 2,
  },
  {
    name: 'Spaghetti',
    price: 17,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 400,
    img: '22.jpg',
    cookingTime: 15,
    orderCounter: 37,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 34,
  },
  {
    name: 'penne pasta',
    price: 17,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 300,
    img: '23.jpg',
    cookingTime: 20,
    orderCounter: 10,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 6,
  },
  {
    name: 'Penny with chicken',
    price: 22,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 500,
    img: '24.jpg',
    cookingTime: 23,
    orderCounter: 16,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 9,
  },
  {
    name: 'manakish',
    price: 7,
    description: ' ',
    category: ['break fast'],
    type: 'food',
    sensitivity: [
      { vegan: true },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 200,
    img: '25.jpg',
    cookingTime: 10,
    orderCounter: 703,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 538,
  },
  {
    name: 'cappy',
    price: 3,
    description: ' ',
    category: ['break fast'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 80,
    img: 'juice.jpg',
    cookingTime: 1,
    orderCounter: 1063,
    ratingSum: 55,
    ratingCounter: 12,
    likes: 758,
  },
];

const SIROTER = [
  {
    name: 'Fresh orange juice',
    price: 16,
    description: ' ',
    category: ['lunch'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 63,
    img: '27.jpg',
    cookingTime: 12,
    orderCounter: 23,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 7,
  },
  {
    name: 'Fresh carrot juice',
    price: 16,
    description: ' ',
    category: ['lunch'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 63,
    img: 'Fresh carrot juice.jpg',
    cookingTime: 12,
    orderCounter: 23,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 7,
  },
  {
    name: 'Lemon juice',
    price: 15,
    description: ' ',
    category: ['break fast'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 63,
    img: 'Lemon juice.jpg',
    cookingTime: 12,
    orderCounter: 23,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 7,
  },
  {
    name: 'Apple juice',
    price: 18,
    description: ' ',
    category: ['break fast'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 63,
    img: 'Apple juice.jpg',
    cookingTime: 12,
    orderCounter: 23,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 7,
  },
  {
    name: 'Strawberry juice',
    price: 16,
    description: ' ',
    category: ['break fast'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 63,
    img: 'Strawberry juice.jpg',
    cookingTime: 12,
    orderCounter: 23,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 7,
  },
  {
    name: 'Mango juice',
    price: 16,
    description: ' ',
    category: ['break fast'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 63,
    img: 'Mango juice.jpg',
    cookingTime: 12,
    orderCounter: 84,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 45,
  },
  {
    name: 'Seasonal pomegranate juice',
    price: 18,
    description: ' ',
    category: ['break fast'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 63,
    img: 'Seasonal pomegranate juice.jpg',
    cookingTime: 12,
    orderCounter: 34,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 9,
  },
  {
    name: 'Seasonal watermelon juice',
    price: 16,
    description: ' ',
    category: ['break fast'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 63,
    img: 'Seasonal watermelon juice.jpg',
    cookingTime: 12,
    orderCounter: 13,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 8,
  },
  {
    name: 'iced coffee',
    price: 15,
    description: ' ',
    category: ['lunch'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 63,
    img: 'iced coffee.jpg',
    cookingTime: 12,
    orderCounter: 293,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 166,
  },
  {
    name: 'Iced Vanilla',
    price: 15,
    description: ' ',
    category: ['dinner'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 63,
    img: 'Iced Vanilla.jpg',
    cookingTime: 12,
    orderCounter: 123,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 47,
  },
  {
    name: 'Iced Chocolate',
    price: 15,
    description: ' ',
    category: ['dinner'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 63,
    img: 'Iced Chocolate.jpg',
    cookingTime: 12,
    orderCounter: 236,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 167,
  },
  {
    name: 'ice tea',
    price: 15,
    description: ' ',
    category: ['lunch'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 63,
    img: 'ice tea.jpg',
    cookingTime: 12,
    orderCounter: 623,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 173,
  },
  {
    name: 'hot chocolate',
    price: 15,
    description: ' ',
    category: ['lunch'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 175,
    img: 'hot chocolate.jpg',
    cookingTime: 12,
    orderCounter: 232,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 72,
  },
  {
    name: 'hot coconut chocolate',
    price: 15,
    description: ' ',
    category: ['lunch'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 184,
    img: 'hot coconut chocolate.jpg',
    cookingTime: 12,
    orderCounter: 253,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 71,
  },
  {
    name: 'Tea',
    price: 10,
    description: ' ',
    category: ['break fast'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 63,
    img: 'tea.jpg',
    cookingTime: 12,
    orderCounter: 1894,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 1052,
  },
  {
    name: 'Mix herbs with honey and ginger',
    price: 15,
    description: ' ',
    category: ['break fast'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 74,
    img: 'Mix herbs with honey and ginger.jpg',
    cookingTime: 12,
    orderCounter: 1031,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 853,
  },
  {
    name: 'latte tea',
    price: 15,
    description: ' ',
    category: ['dinner'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 142,
    img: 'latte tea.jpg',
    cookingTime: 12,
    orderCounter: 611,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 445,
  },
  {
    name: 'French vanilla drink',
    price: 15,
    description: ' ',
    category: ['break fast'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 174,
    img: 'French vanilla drink.jpg',
    cookingTime: 12,
    orderCounter: 323,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 99,
  },
  {
    name: 'french hazelnut drink',
    price: 15,
    description: ' ',
    category: ['break fast'],
    type: 'drink',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: true },
      { milk: false },
      { egg: false },
    ],
    calories: 134,
    img: 'french hazelnut drink.jpg',
    cookingTime: 12,
    orderCounter: 213,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 87,
  },
  {
    name: 'New York cheesecake',
    price: 25,
    description: ' ',
    category: ['dinner'],
    type: 'dessert',
    sensitivity: [
      { vegan: true },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: true },
      { egg: true },
    ],
    calories: 327,
    img: 'New York cheesecake.jpg',
    cookingTime: 12,
    orderCounter: 293,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 97,
  },
  {
    name: 'english cake',
    price: 8,
    description: ' ',
    category: ['dinner'],
    type: 'dessert',
    sensitivity: [
      { vegan: true },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: true },
      { egg: true },
    ],
    calories: 274,
    img: 'english cake.jpg',
    cookingTime: 12,
    orderCounter: 283,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 77,
  },
  {
    name: 'Cookie in the frying pan',
    price: 28,
    description: ' ',
    category: ['dinner'],
    type: 'dessert',
    sensitivity: [
      { vegan: true },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: true },
      { egg: true },
    ],
    calories: 474,
    img: 'Cookie in the frying pan.jpg',
    cookingTime: 12,
    orderCounter: 323,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 157,
  },
  {
    name: 'Belgian waffle',
    price: 25,
    description: ' ',
    category: ['dinner'],
    type: 'dessert',
    sensitivity: [
      { vegan: true },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: true },
      { egg: true },
    ],
    calories: 274,
    img: 'Belgian waffle.jpg',
    cookingTime: 12,
    orderCounter: 243,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 74,
  },
  {
    name: 'brownies',
    price: 25,
    description: ' ',
    category: ['dinner'],
    type: 'dessert',
    sensitivity: [
      { vegan: true },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: true },
      { egg: true },
    ],
    calories: 574,
    img: 'brownies.jpg',
    cookingTime: 12,
    orderCounter: 973,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 748,
  },
  {
    name: 'Hot Chocolate Souffle',
    price: 15,
    description: ' ',
    category: ['dinner'],
    type: 'dessert',
    sensitivity: [
      { vegan: true },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: true },
      { egg: true },
    ],
    calories: 374,
    img: 'Hot Chocolate Souffle.jpg',
    cookingTime: 12,
    orderCounter: 752,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 453,
  },
  {
    name: 'cookies',
    price: 5,
    description: ' ',
    category: ['dinner'],
    type: 'dessert',
    sensitivity: [
      { vegan: true },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: true },
      { egg: true },
    ],
    calories: 274,
    img: 'cookies.jpg',
    cookingTime: 12,
    orderCounter: 197,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 69,
  },
  {
    name: 'Lotus Cheese Cake',
    price: 22,
    description: ' ',
    category: ['dinner'],
    type: 'dessert',
    sensitivity: [
      { vegan: true },
      { gluten: true },
      { seafood: false },
      { nutAllergy: false },
      { milk: true },
      { egg: true },
    ],
    calories: 468,
    img: 'Lotus Cheese Cake.jpg',
    cookingTime: 12,
    orderCounter: 88,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 56,
  },
  {
    name: 'Ali `s mother',
    price: 25,
    description: ' ',
    category: ['dinner'],
    type: 'dessert',
    sensitivity: [
      { vegan: true },
      { gluten: false },
      { seafood: false },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 274,
    img: 'Ali `s mother.jpg',
    cookingTime: 12,
    orderCounter: 76,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 37,
  },
  {
    name: 'Shrimp Noodles',
    price: 65,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: false },
      { seafood: true },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 778,
    img: 'Shrimp Noodles.jpg',
    cookingTime: 12,
    orderCounter: 69,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 13,
  },
  {
    name: 'Cashew Chicken',
    price: 50,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: false },
      { seafood: false },
      { nutAllergy: true },
      { milk: false },
      { egg: false },
    ],
    calories: 861,
    img: 'Cashew Chicken.jpg',
    cookingTime: 12,
    orderCounter: 65,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 41,
  },
  {
    name: 'Shrimp pottery',
    price: 70,
    description: ' ',
    category: ['lunch'],
    type: 'food',
    sensitivity: [
      { vegan: false },
      { gluten: false },
      { seafood: true },
      { nutAllergy: false },
      { milk: false },
      { egg: false },
    ],
    calories: 274,
    img: 'Shrimp pottery.jpg',
    cookingTime: 30,
    orderCounter: 74,
    ratingSum: 5,
    ratingCounter: 1,
    likes: 58,
  },
];

let arr1 = [];
for (let i = 0; i < res.length; i++) {
  arr1[i] = new Restaurant(res[i]);
}

for (let index = 0; index < SHRAK.length; index++) {
  let meal = new Meal(SHRAK[index]);
  meal.save();
  arr1[0].meals.push(meal);
}

for (let index = 0; index < LILAC.length; index++) {
  let meal = new Meal(LILAC[index]);
  meal.save();
  arr1[1].meals.push(meal);
}

for (let index = 0; index < SIROTER.length; index++) {
  let meal = new Meal(SIROTER[index]);
  meal.save();
  arr1[2].meals.push(meal);
}

arr1[0].save();
arr1[1].save();
arr1[2].save();
arr1[3].save();
arr1[4].save();
arr1[5].save();
